// 100+ 아이템 데이터베이스 - 도트 스타일 코디 가챠 게임

export type ItemRarity = "common" | "rare" | "epic" | "legendary" | "mythic";
export type ItemCategory = "hat" | "hair" | "face" | "eyes" | "mouth" | "accessory" | "clothes" | "shoes" | "background" | "effect" | "pet" | "furniture";

export interface GameItem {
  id: string;
  name: string;
  category: ItemCategory;
  rarity: ItemRarity;
  description: string;
  // 도트 아트 스타일 - SVG path 또는 pixel data
  pixelArt: string; // SVG string or emoji fallback
  // 슬라임에 장착 시 위치 조정
  position: { x: number; y: number };
  scale: number;
  zIndex: number;
  // 게임 데이터
  price: number; // 골드 가격
  gemPrice?: number; // 젬 가격 (프리미엄)
  dropRate: number; // 드롭 확률 (0-100)
  stats?: {
    happiness?: number;
    luck?: number;
    charm?: number;
  };
}

// 등급별 색상 및 설정
export const RARITY_CONFIG: Record<ItemRarity, { color: string; glow: string; dropRate: number; priceMultiplier: number }> = {
  common: { color: "#9E9E9E", glow: "rgba(158,158,158,0.3)", dropRate: 50, priceMultiplier: 1 },
  rare: { color: "#2196F3", glow: "rgba(33,150,243,0.4)", dropRate: 30, priceMultiplier: 2 },
  epic: { color: "#9C27B0", glow: "rgba(156,39,176,0.5)", dropRate: 15, priceMultiplier: 5 },
  legendary: { color: "#FF9800", glow: "rgba(255,152,0,0.6)", dropRate: 4, priceMultiplier: 15 },
  mythic: { color: "#E91E63", glow: "rgba(233,30,99,0.7)", dropRate: 1, priceMultiplier: 50 },
};

// 카테고리 설정
export const CATEGORY_CONFIG: Record<ItemCategory, { name: string; icon: string; defaultPosition: { x: number; y: number }; defaultZIndex: number }> = {
  hat: { name: "모자", icon: "🎩", defaultPosition: { x: 0, y: -45 }, defaultZIndex: 100 },
  hair: { name: "헤어", icon: "💇", defaultPosition: { x: 0, y: -35 }, defaultZIndex: 90 },
  face: { name: "얼굴", icon: "😊", defaultPosition: { x: 0, y: 0 }, defaultZIndex: 80 },
  eyes: { name: "눈", icon: "👀", defaultPosition: { x: 0, y: -5 }, defaultZIndex: 85 },
  mouth: { name: "입", icon: "👄", defaultPosition: { x: 0, y: 15 }, defaultZIndex: 75 },
  accessory: { name: "악세서리", icon: "💎", defaultPosition: { x: 25, y: -10 }, defaultZIndex: 95 },
  clothes: { name: "의상", icon: "👕", defaultPosition: { x: 0, y: 20 }, defaultZIndex: 70 },
  shoes: { name: "신발", icon: "👟", defaultPosition: { x: 0, y: 55 }, defaultZIndex: 60 },
  background: { name: "배경", icon: "🖼️", defaultPosition: { x: 0, y: 0 }, defaultZIndex: 0 },
  effect: { name: "이펙트", icon: "✨", defaultPosition: { x: 0, y: 0 }, defaultZIndex: 200 },
  pet: { name: "펫", icon: "🐾", defaultPosition: { x: 50, y: 30 }, defaultZIndex: 50 },
  furniture: { name: "가구", icon: "🪑", defaultPosition: { x: 0, y: 0 }, defaultZIndex: 10 },
};

// 도트 아트 SVG 생성 헬퍼
function createPixelSvg(pixels: string[], colors: Record<string, string>, width: number = 16, height: number = 16): string {
  let svg = `<svg viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg" style="image-rendering: pixelated;">`;
  pixels.forEach((row, y) => {
    row.split("").forEach((char, x) => {
      if (char !== "." && colors[char]) {
        svg += `<rect x="${x}" y="${y}" width="1" height="1" fill="${colors[char]}"/>`;
      }
    });
  });
  svg += "</svg>";
  return svg;
}

// ============================================
// 100+ 아이템 데이터
// ============================================

export const ITEMS_DATABASE: GameItem[] = [
  // ==================== 모자 (HAT) - 20개 ====================
  {
    id: "hat_crown_gold",
    name: "황금 왕관",
    category: "hat",
    rarity: "legendary",
    description: "진정한 슬라임 왕의 왕관",
    pixelArt: createPixelSvg([
      "................",
      "..G...G...G.....",
      "..GG.GGG.GG.....",
      "..GGGGGGGGG.....",
      "...GGGGGGG......",
      "...YYYYYYYYY....",
      "................",
    ], { G: "#FFD700", Y: "#FFF176" }),
    position: { x: 0, y: -48 },
    scale: 1.2,
    zIndex: 100,
    price: 5000,
    dropRate: 2,
    stats: { charm: 50, luck: 20 },
  },
  {
    id: "hat_beanie_blue",
    name: "파란 비니",
    category: "hat",
    rarity: "common",
    description: "따뜻한 파란색 비니",
    pixelArt: createPixelSvg([
      "....BBBBB.......",
      "...BBBBBBB......",
      "..BBBBBBBBB.....",
      "..BWBWBWBWB.....",
      "................",
    ], { B: "#2196F3", W: "#BBDEFB" }),
    position: { x: 0, y: -42 },
    scale: 1,
    zIndex: 100,
    price: 100,
    dropRate: 15,
    stats: { happiness: 5 },
  },
  {
    id: "hat_wizard",
    name: "마법사 모자",
    category: "hat",
    rarity: "epic",
    description: "신비로운 마법사의 모자",
    pixelArt: createPixelSvg([
      ".......P........",
      "......PPP.......",
      ".....PPPPP......",
      "....PPPPPPP.....",
      "...PPPPPPPPP....",
      "..PPPPSPPPPPP...",
      ".PPPPPPPPPPPPP..",
      "PPPPPPPPPPPPPPPP",
    ], { P: "#7B1FA2", S: "#FFD700" }),
    position: { x: 0, y: -55 },
    scale: 1.1,
    zIndex: 100,
    price: 1500,
    dropRate: 5,
    stats: { luck: 30 },
  },
  {
    id: "hat_ribbon_pink",
    name: "핑크 리본",
    category: "hat",
    rarity: "rare",
    description: "귀여운 핑크색 리본",
    pixelArt: createPixelSvg([
      "..PP.....PP.....",
      ".PPPP...PPPP....",
      "PPPPPPPPPPPP....",
      ".PPPP...PPPP....",
      "..PP.....PP.....",
    ], { P: "#F48FB1" }),
    position: { x: 0, y: -40 },
    scale: 1,
    zIndex: 100,
    price: 300,
    dropRate: 10,
    stats: { charm: 15 },
  },
  {
    id: "hat_cap_red",
    name: "빨간 야구모자",
    category: "hat",
    rarity: "common",
    description: "스포티한 빨간 야구모자",
    pixelArt: createPixelSvg([
      "....RRRRRR......",
      "...RRRRRRRR.....",
      "..RRRRRRRRRR....",
      "..RRRRRRRRRRRR..",
      "................",
    ], { R: "#F44336" }),
    position: { x: 0, y: -42 },
    scale: 1,
    zIndex: 100,
    price: 80,
    dropRate: 18,
  },
  {
    id: "hat_flower_crown",
    name: "꽃 화관",
    category: "hat",
    rarity: "rare",
    description: "봄의 기운이 담긴 화관",
    pixelArt: createPixelSvg([
      "..R.Y.P.R.Y.....",
      ".GRGYGPGRGR.....",
      "..GGGGGGGGG.....",
    ], { R: "#E91E63", Y: "#FFEB3B", P: "#9C27B0", G: "#4CAF50" }),
    position: { x: 0, y: -40 },
    scale: 1,
    zIndex: 100,
    price: 400,
    dropRate: 8,
    stats: { happiness: 20, charm: 10 },
  },
  {
    id: "hat_pirate",
    name: "해적 모자",
    category: "hat",
    rarity: "epic",
    description: "전설의 해적 선장 모자",
    pixelArt: createPixelSvg([
      "......WWW.......",
      ".....WWWWW......",
      "...BBBBBBBBB....",
      "..BBBBBBBBBBB...",
      ".BBBBBBBBBBBBB..",
      "BBBBBGGGBBBBBBB.",
    ], { B: "#212121", W: "#FAFAFA", G: "#FFD700" }),
    position: { x: 0, y: -50 },
    scale: 1.1,
    zIndex: 100,
    price: 1200,
    dropRate: 5,
    stats: { luck: 25 },
  },
  {
    id: "hat_chef",
    name: "셰프 모자",
    category: "hat",
    rarity: "rare",
    description: "요리사의 전문 모자",
    pixelArt: createPixelSvg([
      "....WWWWW.......",
      "...WWWWWWW......",
      "..WWWWWWWWW.....",
      "..WWWWWWWWW.....",
      "...WWWWWWW......",
      "...WWWWWWW......",
    ], { W: "#FAFAFA" }),
    position: { x: 0, y: -52 },
    scale: 1,
    zIndex: 100,
    price: 350,
    dropRate: 9,
    stats: { happiness: 10 },
  },
  {
    id: "hat_cat_ears",
    name: "고양이 귀",
    category: "hat",
    rarity: "rare",
    description: "귀여운 고양이 귀 머리띠",
    pixelArt: createPixelSvg([
      "..PP.....PP.....",
      ".PPPP...PPPP....",
      "PPPPP...PPPPP...",
      ".BBBBBBBBBBB....",
    ], { P: "#F48FB1", B: "#212121" }),
    position: { x: 0, y: -42 },
    scale: 1,
    zIndex: 100,
    price: 500,
    dropRate: 8,
    stats: { charm: 20 },
  },
  {
    id: "hat_bunny_ears",
    name: "토끼 귀",
    category: "hat",
    rarity: "rare",
    description: "폭신폭신한 토끼 귀",
    pixelArt: createPixelSvg([
      "..WW.....WW.....",
      "..WWW...WWW.....",
      "..WWWW.WWWW.....",
      "..WPWW.WPWW.....",
      "..WWWW.WWWW.....",
      "...WWW.WWW......",
      "....BBBBB.......",
    ], { W: "#FAFAFA", P: "#FFCDD2", B: "#E0E0E0" }),
    position: { x: 0, y: -55 },
    scale: 1,
    zIndex: 100,
    price: 450,
    dropRate: 8,
    stats: { charm: 18, happiness: 5 },
  },
  {
    id: "hat_halo",
    name: "천사 후광",
    category: "hat",
    rarity: "legendary",
    description: "신성한 천사의 후광",
    pixelArt: createPixelSvg([
      "....GGGGG.......",
      "...GG...GG......",
      "..GG.....GG.....",
      "..GG.....GG.....",
      "...GG...GG......",
      "....GGGGG.......",
    ], { G: "#FFD700" }),
    position: { x: 0, y: -55 },
    scale: 1.2,
    zIndex: 100,
    price: 4000,
    dropRate: 2,
    stats: { charm: 40, luck: 30, happiness: 20 },
  },
  {
    id: "hat_devil_horns",
    name: "악마 뿔",
    category: "hat",
    rarity: "epic",
    description: "작은 악마의 뿔",
    pixelArt: createPixelSvg([
      "..R.......R.....",
      ".RR.......RR....",
      "RRR.......RRR...",
      ".RRR.....RRR....",
      "..RRRRRRRRR.....",
    ], { R: "#D32F2F" }),
    position: { x: 0, y: -45 },
    scale: 1,
    zIndex: 100,
    price: 1000,
    dropRate: 6,
    stats: { luck: 15 },
  },
  {
    id: "hat_cowboy",
    name: "카우보이 모자",
    category: "hat",
    rarity: "rare",
    description: "서부의 카우보이 모자",
    pixelArt: createPixelSvg([
      "....BBBBB.......",
      "...BBBBBBB......",
      "..BBBBBBBBB.....",
      "BBBBBBBBBBBBB...",
      "..BBBBBBBBB.....",
    ], { B: "#8D6E63" }),
    position: { x: 0, y: -45 },
    scale: 1.1,
    zIndex: 100,
    price: 380,
    dropRate: 9,
  },
  {
    id: "hat_santa",
    name: "산타 모자",
    category: "hat",
    rarity: "epic",
    description: "크리스마스 산타 모자",
    pixelArt: createPixelSvg([
      "........W.......",
      ".......WW.......",
      "......RRR.......",
      ".....RRRRR......",
      "....RRRRRRR.....",
      "...WWWWWWWWW....",
    ], { R: "#F44336", W: "#FAFAFA" }),
    position: { x: 0, y: -50 },
    scale: 1,
    zIndex: 100,
    price: 800,
    dropRate: 6,
    stats: { happiness: 25 },
  },
  {
    id: "hat_party",
    name: "파티 고깔모자",
    category: "hat",
    rarity: "common",
    description: "파티용 고깔모자",
    pixelArt: createPixelSvg([
      ".......Y........",
      "......YYY.......",
      ".....YYYYY......",
      "....YYYYYYY.....",
      "...GRGRGRGR.....",
    ], { Y: "#FFEB3B", G: "#4CAF50", R: "#F44336" }),
    position: { x: 0, y: -50 },
    scale: 1,
    zIndex: 100,
    price: 60,
    dropRate: 20,
    stats: { happiness: 10 },
  },
  {
    id: "hat_graduation",
    name: "학사모",
    category: "hat",
    rarity: "epic",
    description: "졸업을 축하하는 학사모",
    pixelArt: createPixelSvg([
      "BBBBBBBBBBBBBBBB",
      ".BBBBBBBBBBBBBB.",
      "..BBBBBBBBBBBB..",
      "...BBBBGGBBBB...",
      "...BBBBBBBBBB...",
      "......GGG.......",
    ], { B: "#212121", G: "#FFD700" }),
    position: { x: 0, y: -48 },
    scale: 1.1,
    zIndex: 100,
    price: 1100,
    dropRate: 5,
    stats: { luck: 20 },
  },
  {
    id: "hat_ninja",
    name: "닌자 머리띠",
    category: "hat",
    rarity: "rare",
    description: "은밀한 닌자의 머리띠",
    pixelArt: createPixelSvg([
      "RR..........RR..",
      "RRRRRRRRRRRRRR..",
      "..RRRRRRRRRR....",
    ], { R: "#D32F2F" }),
    position: { x: 0, y: -38 },
    scale: 1,
    zIndex: 100,
    price: 420,
    dropRate: 9,
    stats: { luck: 12 },
  },
  {
    id: "hat_crown_princess",
    name: "프린세스 티아라",
    category: "hat",
    rarity: "legendary",
    description: "공주님의 아름다운 티아라",
    pixelArt: createPixelSvg([
      "..S...S...S.....",
      "..P.S.P.S.P.....",
      "..PPPPPPPPP.....",
      "...PPPPPPP......",
    ], { P: "#E1BEE7", S: "#E91E63" }),
    position: { x: 0, y: -42 },
    scale: 1,
    zIndex: 100,
    price: 4500,
    dropRate: 2,
    stats: { charm: 45, happiness: 15 },
  },
  {
    id: "hat_mushroom",
    name: "버섯 모자",
    category: "hat",
    rarity: "rare",
    description: "귀여운 버섯 모양 모자",
    pixelArt: createPixelSvg([
      "....RRRRR.......",
      "...RWRWRWR......",
      "..RRRRRRRRR.....",
      "...BBBBBBB......",
      "....BBBBB.......",
    ], { R: "#F44336", W: "#FAFAFA", B: "#BCAAA4" }),
    position: { x: 0, y: -48 },
    scale: 1,
    zIndex: 100,
    price: 350,
    dropRate: 9,
    stats: { happiness: 12 },
  },
  {
    id: "hat_astronaut",
    name: "우주비행사 헬멧",
    category: "hat",
    rarity: "mythic",
    description: "우주를 탐험하는 헬멧",
    pixelArt: createPixelSvg([
      "...WWWWWWW......",
      "..WWWWWWWWW.....",
      ".WWWBBBBBWWW....",
      ".WWBBBBBBWWW....",
      ".WWWBBBBBWWW....",
      "..WWWWWWWWW.....",
      "...WWWWWWW......",
    ], { W: "#ECEFF1", B: "#263238" }),
    position: { x: 0, y: -52 },
    scale: 1.2,
    zIndex: 100,
    price: 15000,
    dropRate: 0.5,
    stats: { luck: 50, charm: 30 },
  },

  // ==================== 얼굴 (FACE) - 15개 ====================
  {
    id: "face_glasses",
    name: "둥근 안경",
    category: "face",
    rarity: "common",
    description: "지적인 느낌의 둥근 안경",
    pixelArt: createPixelSvg([
      ".BBB...BBB......",
      "B...B.B...B.....",
      "B...BBB...B.....",
      ".BBB...BBB......",
    ], { B: "#212121" }),
    position: { x: 0, y: -5 },
    scale: 1,
    zIndex: 85,
    price: 80,
    dropRate: 18,
    stats: { luck: 5 },
  },
  {
    id: "face_sunglasses",
    name: "멋진 선글라스",
    category: "face",
    rarity: "rare",
    description: "쿨한 선글라스",
    pixelArt: createPixelSvg([
      "BBBBB.BBBBB.....",
      "BBBBBBBBBBB.....",
      ".BBB...BBB......",
    ], { B: "#212121" }),
    position: { x: 0, y: -5 },
    scale: 1,
    zIndex: 85,
    price: 300,
    dropRate: 10,
    stats: { charm: 15 },
  },
  {
    id: "face_mask_cat",
    name: "고양이 마스크",
    category: "face",
    rarity: "rare",
    description: "귀여운 고양이 마스크",
    pixelArt: createPixelSvg([
      "..W.....W.......",
      ".WWW...WWW......",
      "WWWWWWWWWWW.....",
      "W.WW.W.WW.W.....",
      "WWWWWWWWWWW.....",
      ".WWWWWWWWW......",
      "...W...W........",
    ], { W: "#FAFAFA" }),
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 85,
    price: 400,
    dropRate: 8,
    stats: { charm: 18 },
  },
  {
    id: "face_blush",
    name: "핑크 볼터치",
    category: "face",
    rarity: "common",
    description: "귀여운 핑크 볼",
    pixelArt: createPixelSvg([
      "PP.......PP.....",
      "PPP.....PPP.....",
      "PP.......PP.....",
    ], { P: "#F8BBD9" }),
    position: { x: 0, y: 10 },
    scale: 1,
    zIndex: 85,
    price: 50,
    dropRate: 20,
    stats: { charm: 8 },
  },
  {
    id: "face_monocle",
    name: "모노클",
    category: "face",
    rarity: "epic",
    description: "신사의 모노클",
    pixelArt: createPixelSvg([
      "...GGG..........",
      "..G...G.........",
      "..G...G.........",
      "...GGG..........",
      "....G...........",
    ], { G: "#FFD700" }),
    position: { x: -15, y: -5 },
    scale: 1,
    zIndex: 85,
    price: 1200,
    dropRate: 5,
    stats: { charm: 25, luck: 10 },
  },
  {
    id: "face_star_eyes",
    name: "별빛 눈",
    category: "face",
    rarity: "legendary",
    description: "반짝이는 별빛 눈",
    pixelArt: createPixelSvg([
      "..Y...Y.........",
      ".YYY.YYY........",
      "YYYYY.YYYYY.....",
      ".YYY.YYY........",
      "..Y...Y.........",
    ], { Y: "#FFD700" }),
    position: { x: 0, y: -8 },
    scale: 1,
    zIndex: 85,
    price: 3500,
    dropRate: 2,
    stats: { charm: 35, happiness: 20 },
  },
  {
    id: "face_heart_eyes",
    name: "하트 눈",
    category: "face",
    rarity: "epic",
    description: "사랑스러운 하트 눈",
    pixelArt: createPixelSvg([
      ".PP.PP.PP.PP....",
      "PPPPPPPPPPPPP...",
      ".PPPPP.PPPPP....",
      "..PPP...PPP.....",
      "...P.....P......",
    ], { P: "#E91E63" }),
    position: { x: 0, y: -8 },
    scale: 1,
    zIndex: 85,
    price: 1000,
    dropRate: 6,
    stats: { charm: 30 },
  },
  {
    id: "face_mask_medical",
    name: "마스크",
    category: "face",
    rarity: "common",
    description: "깨끗한 마스크",
    pixelArt: createPixelSvg([
      "B.........B.....",
      ".BWWWWWWWB......",
      ".BWWWWWWWB......",
      "..BWWWWWB.......",
      "...BBBBB........",
    ], { W: "#FAFAFA", B: "#90CAF9" }),
    position: { x: 0, y: 8 },
    scale: 1,
    zIndex: 85,
    price: 40,
    dropRate: 22,
  },
  {
    id: "face_mustache",
    name: "콧수염",
    category: "face",
    rarity: "rare",
    description: "멋진 콧수염",
    pixelArt: createPixelSvg([
      "BBB.....BBB.....",
      ".BBBBBBBBB......",
      "..BBBBBBB.......",
    ], { B: "#5D4037" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 85,
    price: 250,
    dropRate: 10,
    stats: { charm: 12 },
  },
  {
    id: "face_tears",
    name: "눈물",
    category: "face",
    rarity: "rare",
    description: "반짝이는 눈물",
    pixelArt: createPixelSvg([
      "..B.....B.......",
      ".BB....BB.......",
      "BBB....BBB......",
      ".BB....BB.......",
      "..B.....B.......",
    ], { B: "#64B5F6" }),
    position: { x: 0, y: 5 },
    scale: 1,
    zIndex: 85,
    price: 280,
    dropRate: 10,
    stats: { happiness: -5, charm: 10 },
  },
  {
    id: "face_freckles",
    name: "주근깨",
    category: "face",
    rarity: "common",
    description: "귀여운 주근깨",
    pixelArt: createPixelSvg([
      ".B.B.....B.B....",
      "..B.......B.....",
      ".B.B.....B.B....",
    ], { B: "#BCAAA4" }),
    position: { x: 0, y: 5 },
    scale: 1,
    zIndex: 85,
    price: 60,
    dropRate: 18,
    stats: { charm: 5 },
  },
  {
    id: "face_3d_glasses",
    name: "3D 안경",
    category: "face",
    rarity: "rare",
    description: "레트로 3D 안경",
    pixelArt: createPixelSvg([
      ".RRR...BBB......",
      "RRRRRBBBBB......",
      ".RRR...BBB......",
    ], { R: "#F44336", B: "#2196F3" }),
    position: { x: 0, y: -5 },
    scale: 1,
    zIndex: 85,
    price: 350,
    dropRate: 9,
    stats: { luck: 10 },
  },
  {
    id: "face_bandaid",
    name: "반창고",
    category: "face",
    rarity: "common",
    description: "작은 반창고",
    pixelArt: createPixelSvg([
      "..BBBBB.........",
      ".BWWWWWB........",
      "..BBBBB.........",
    ], { B: "#FFCC80", W: "#FAFAFA" }),
    position: { x: 10, y: 5 },
    scale: 1,
    zIndex: 85,
    price: 30,
    dropRate: 22,
  },
  {
    id: "face_nerd_glasses",
    name: "너드 안경",
    category: "face",
    rarity: "rare",
    description: "두꺼운 너드 안경",
    pixelArt: createPixelSvg([
      "BBBBB.BBBBB.....",
      "B...B.B...B.....",
      "B...BBB...B.....",
      "BBBBB.BBBBB.....",
    ], { B: "#212121" }),
    position: { x: 0, y: -5 },
    scale: 1,
    zIndex: 85,
    price: 280,
    dropRate: 10,
    stats: { luck: 15 },
  },
  {
    id: "face_cyber_visor",
    name: "사이버 바이저",
    category: "face",
    rarity: "mythic",
    description: "미래에서 온 바이저",
    pixelArt: createPixelSvg([
      "CCCCCCCCCCCCC...",
      "CGGGGGGGGGGCC...",
      "CGGGGGGGGGGCC...",
      "CCCCCCCCCCCCC...",
    ], { C: "#37474F", G: "#00E676" }),
    position: { x: 0, y: -5 },
    scale: 1.1,
    zIndex: 85,
    price: 12000,
    dropRate: 0.5,
    stats: { charm: 40, luck: 30 },
  },

  // ==================== 의상 (CLOTHES) - 20개 ====================
  {
    id: "clothes_tshirt_white",
    name: "흰색 티셔츠",
    category: "clothes",
    rarity: "common",
    description: "기본 흰색 티셔츠",
    pixelArt: createPixelSvg([
      "..WWWWWWWW......",
      ".WWWWWWWWWW.....",
      "WWWWWWWWWWWW....",
      ".WWWWWWWWWW.....",
      "..WWWWWWWW......",
      "..WWWWWWWW......",
    ], { W: "#FAFAFA" }),
    position: { x: 0, y: 15 },
    scale: 1,
    zIndex: 70,
    price: 50,
    dropRate: 20,
  },
  {
    id: "clothes_hoodie_gray",
    name: "회색 후드티",
    category: "clothes",
    rarity: "common",
    description: "편안한 회색 후드티",
    pixelArt: createPixelSvg([
      "..GGGGGGG.......",
      ".GGGGGGGGG......",
      "GGGGWWWGGGG.....",
      "GGGGGGGGGGG.....",
      ".GGGGGGGGG......",
      ".GGGGGGGGG......",
      "..GGGGGGG.......",
    ], { G: "#9E9E9E", W: "#757575" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 120,
    dropRate: 16,
    stats: { happiness: 5 },
  },
  {
    id: "clothes_dress_pink",
    name: "핑크 드레스",
    category: "clothes",
    rarity: "rare",
    description: "귀여운 핑크 드레스",
    pixelArt: createPixelSvg([
      "..PPPPPPP.......",
      ".PPPPPPPPP......",
      ".PPPPPPPPP......",
      "PPPPPPPPPPP.....",
      "PPPPPPPPPPP.....",
      "PPPPPPPPPPP.....",
      "P.PPPPPPP.P.....",
    ], { P: "#F48FB1" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 400,
    dropRate: 9,
    stats: { charm: 20 },
  },
  {
    id: "clothes_suit",
    name: "정장",
    category: "clothes",
    rarity: "epic",
    description: "고급스러운 정장",
    pixelArt: createPixelSvg([
      "..BWWWWWB.......",
      ".BBWWWWWBB......",
      "BBBWWWWWBBB.....",
      "BBBBBBBBBBB.....",
      ".BBBBBBBBB......",
      ".BBBBBBBBB......",
      "..BBBBBBB.......",
    ], { B: "#212121", W: "#FAFAFA" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 1500,
    dropRate: 5,
    stats: { charm: 30 },
  },
  {
    id: "clothes_overalls",
    name: "멜빵바지",
    category: "clothes",
    rarity: "rare",
    description: "귀여운 멜빵바지",
    pixelArt: createPixelSvg([
      ".B.......B......",
      ".BBBBBBBBB......",
      "BBBBBBBBBBB.....",
      "BBBBBBBBBBB.....",
      "BB.BBBBB.BB.....",
      "BB.BBBBB.BB.....",
    ], { B: "#1976D2" }),
    position: { x: 0, y: 10 },
    scale: 1,
    zIndex: 70,
    price: 350,
    dropRate: 9,
    stats: { happiness: 10 },
  },
  {
    id: "clothes_kimono",
    name: "기모노",
    category: "clothes",
    rarity: "epic",
    description: "전통 일본 기모노",
    pixelArt: createPixelSvg([
      "..RRRRRRR.......",
      ".RRRRRRRRR......",
      "RRRRGGRRRRRR....",
      "RRRRRRRRRRRR....",
      ".RRRRRRRRRR.....",
      ".RRRRRRRRRR.....",
      "..RRRRRRRR......",
    ], { R: "#D32F2F", G: "#FFD700" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 1200,
    dropRate: 5,
    stats: { charm: 25 },
  },
  {
    id: "clothes_hanbok",
    name: "한복",
    category: "clothes",
    rarity: "legendary",
    description: "아름다운 한복",
    pixelArt: createPixelSvg([
      "..PPPPPPP.......",
      ".PPPYYPPPP......",
      "PPPPPPPPPPP.....",
      "BBBBBBBBBBB.....",
      "BBBBBBBBBBBB....",
      "BBBBBBBBBBBBB...",
      ".BBBBBBBBBBB....",
    ], { P: "#E91E63", Y: "#FFEB3B", B: "#3F51B5" }),
    position: { x: 0, y: 10 },
    scale: 1.1,
    zIndex: 70,
    price: 5000,
    dropRate: 2,
    stats: { charm: 50, happiness: 20 },
  },
  {
    id: "clothes_armor",
    name: "기사 갑옷",
    category: "clothes",
    rarity: "legendary",
    description: "빛나는 기사의 갑옷",
    pixelArt: createPixelSvg([
      "..GGGGGGG.......",
      ".GGGGGGGGG......",
      "GGGGGGGGGGG.....",
      "GGGGYYGGGGG.....",
      ".GGGGGGGGG......",
      ".GGGGGGGGG......",
      "..GGGGGGG.......",
    ], { G: "#90A4AE", Y: "#FFD700" }),
    position: { x: 0, y: 12 },
    scale: 1.1,
    zIndex: 70,
    price: 4500,
    dropRate: 2,
    stats: { luck: 30, charm: 25 },
  },
  {
    id: "clothes_pajama",
    name: "파자마",
    category: "clothes",
    rarity: "common",
    description: "편안한 파자마",
    pixelArt: createPixelSvg([
      "..BWBWBWB.......",
      ".BWBWBWBWB......",
      "BWBWBWBWBWB.....",
      ".BWBWBWBWB......",
      ".BWBWBWBWB......",
      "..BWBWBWB.......",
    ], { B: "#90CAF9", W: "#FAFAFA" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 80,
    dropRate: 18,
    stats: { happiness: 15 },
  },
  {
    id: "clothes_sailor",
    name: "세일러복",
    category: "clothes",
    rarity: "rare",
    description: "귀여운 세일러복",
    pixelArt: createPixelSvg([
      "BB.......BB.....",
      ".BWWWWWWWB......",
      "BWWWWWWWWWB.....",
      "BWWWRRRWWWB.....",
      ".BBBBBBBBB......",
      ".BBBBBBBBB......",
    ], { B: "#1976D2", W: "#FAFAFA", R: "#F44336" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 450,
    dropRate: 8,
    stats: { charm: 18 },
  },
  {
    id: "clothes_sweater_heart",
    name: "하트 스웨터",
    category: "clothes",
    rarity: "rare",
    description: "하트 무늬 스웨터",
    pixelArt: createPixelSvg([
      "..PPPPPPP.......",
      ".PPPPPPPPP......",
      "PPPRR.RRPPP.....",
      "PPPRRRRRRPPP....",
      ".PPPRRRRRPP.....",
      ".PPPP.RR.PP.....",
      "..PPPPPPP.......",
    ], { P: "#F48FB1", R: "#D32F2F" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 380,
    dropRate: 9,
    stats: { charm: 15, happiness: 8 },
  },
  {
    id: "clothes_vampire_cape",
    name: "뱀파이어 망토",
    category: "clothes",
    rarity: "epic",
    description: "어둠의 뱀파이어 망토",
    pixelArt: createPixelSvg([
      "B...........B...",
      "BB.........BB...",
      ".BRRRRRRRRB.....",
      "..BRRRRRRB......",
      "...BRRRRB.......",
      "....BRRB........",
      ".....BB.........",
    ], { B: "#212121", R: "#B71C1C" }),
    position: { x: 0, y: 8 },
    scale: 1.1,
    zIndex: 70,
    price: 1100,
    dropRate: 5,
    stats: { charm: 22, luck: 10 },
  },
  {
    id: "clothes_maid",
    name: "메이드복",
    category: "clothes",
    rarity: "epic",
    description: "클래식 메이드복",
    pixelArt: createPixelSvg([
      "..BBBBBBB.......",
      ".BWWWWWWWB......",
      "BWWWBBBWWWB.....",
      "BWWWWWWWWWB.....",
      ".BWWWWWWWB......",
      ".BWWBWBWWB......",
      "..BBBBBBB.......",
    ], { B: "#212121", W: "#FAFAFA" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 1000,
    dropRate: 6,
    stats: { charm: 28 },
  },
  {
    id: "clothes_doctor",
    name: "의사 가운",
    category: "clothes",
    rarity: "rare",
    description: "깨끗한 의사 가운",
    pixelArt: createPixelSvg([
      "..WWWWWWW.......",
      ".WWWWWWWWW......",
      "WWWWWWWWWWW.....",
      "WWWWWWWWWWW.....",
      ".WWWWWWWWW......",
      ".WWWWWWWWW......",
      "..WWWWWWW.......",
    ], { W: "#FAFAFA" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 400,
    dropRate: 9,
    stats: { luck: 12 },
  },
  {
    id: "clothes_spacesuit",
    name: "우주복",
    category: "clothes",
    rarity: "mythic",
    description: "우주 탐험용 우주복",
    pixelArt: createPixelSvg([
      "..WWWWWWW.......",
      ".WWWWWWWWW......",
      "WWWWOOWWWWW.....",
      "WWWWWWWWWWW.....",
      ".WWWWWWWWW......",
      ".WWWWWWWWW......",
      "..WWWWWWW.......",
    ], { W: "#ECEFF1", O: "#FF9800" }),
    position: { x: 0, y: 12 },
    scale: 1.1,
    zIndex: 70,
    price: 15000,
    dropRate: 0.5,
    stats: { charm: 45, luck: 35 },
  },
  {
    id: "clothes_jersey",
    name: "유니폼",
    category: "clothes",
    rarity: "common",
    description: "스포츠 유니폼",
    pixelArt: createPixelSvg([
      "..BBBBBBB.......",
      ".BBBBBBBBB......",
      "BBBWWWWBBB......",
      "BBB.10.BBB......",
      ".BBBBBBBBB......",
      ".BBBBBBBBB......",
    ], { B: "#F44336", W: "#FAFAFA" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 100,
    dropRate: 16,
    stats: { happiness: 8 },
  },
  {
    id: "clothes_raincoat",
    name: "비옷",
    category: "clothes",
    rarity: "common",
    description: "노란 비옷",
    pixelArt: createPixelSvg([
      "..YYYYYYY.......",
      ".YYYYYYYYY......",
      "YYYYYYYYYYY.....",
      "YYYYYYYYYYY.....",
      ".YYYYYYYYY......",
      ".YYYYYYYYY......",
    ], { Y: "#FFEB3B" }),
    position: { x: 0, y: 10 },
    scale: 1,
    zIndex: 70,
    price: 90,
    dropRate: 17,
    stats: { happiness: 5 },
  },
  {
    id: "clothes_prince",
    name: "왕자 의상",
    category: "clothes",
    rarity: "legendary",
    description: "고귀한 왕자 의상",
    pixelArt: createPixelSvg([
      "..BWWWWWB.......",
      ".BBWGGGWBB......",
      "BBBWGGGWBBB.....",
      "BBBWWWWWBBB.....",
      ".BBBGGGBBB......",
      ".BBBBBBBBB......",
      "..BBBBBBB.......",
    ], { B: "#1A237E", W: "#FAFAFA", G: "#FFD700" }),
    position: { x: 0, y: 12 },
    scale: 1.1,
    zIndex: 70,
    price: 4800,
    dropRate: 2,
    stats: { charm: 48, luck: 20 },
  },
  {
    id: "clothes_witch",
    name: "마녀 드레스",
    category: "clothes",
    rarity: "epic",
    description: "신비로운 마녀 드레스",
    pixelArt: createPixelSvg([
      "..PPPPPPP.......",
      ".PPPPPPPPP......",
      "PPPPSSPPPPP.....",
      "PPPPPPPPPPP.....",
      "PPPP.S.PPPP.....",
      "PPP.SSS.PPP.....",
      "PP.SSSSS.PP.....",
    ], { P: "#4A148C", S: "#FFD700" }),
    position: { x: 0, y: 12 },
    scale: 1,
    zIndex: 70,
    price: 1300,
    dropRate: 5,
    stats: { luck: 25, charm: 20 },
  },
  {
    id: "clothes_angel",
    name: "천사 드레스",
    category: "clothes",
    rarity: "legendary",
    description: "순백의 천사 드레스",
    pixelArt: createPixelSvg([
      "..WWWWWWW.......",
      ".WWWGGGWWW......",
      "WWWWGGGWWWW.....",
      "WWWWWWWWWWW.....",
      ".WWWWWWWWW......",
      ".WWWWWWWWW......",
      "W.WWWWWWW.W.....",
    ], { W: "#FAFAFA", G: "#FFD700" }),
    position: { x: 0, y: 12 },
    scale: 1.1,
    zIndex: 70,
    price: 5500,
    dropRate: 1.5,
    stats: { charm: 50, happiness: 30 },
  },

  // ==================== 악세서리 (ACCESSORY) - 15개 ====================
  {
    id: "acc_necklace_gold",
    name: "골드 목걸이",
    category: "accessory",
    rarity: "rare",
    description: "빛나는 금 목걸이",
    pixelArt: createPixelSvg([
      "....GGG.........",
      "...G...G........",
      "...G.G.G........",
      "....GGG.........",
    ], { G: "#FFD700" }),
    position: { x: 0, y: 25 },
    scale: 1,
    zIndex: 95,
    price: 500,
    dropRate: 8,
    stats: { charm: 18 },
  },
  {
    id: "acc_wings_angel",
    name: "천사 날개",
    category: "accessory",
    rarity: "legendary",
    description: "신성한 천사의 날개",
    pixelArt: createPixelSvg([
      "WW.......WW.....",
      "WWW.....WWW.....",
      "WWWW...WWWW.....",
      "WWWWW.WWWWW.....",
      ".WWWW.WWWW......",
      "..WWW.WWW.......",
    ], { W: "#FAFAFA" }),
    position: { x: 0, y: 0 },
    scale: 1.3,
    zIndex: 65,
    price: 6000,
    dropRate: 1.5,
    stats: { charm: 50, happiness: 25 },
  },
  {
    id: "acc_wings_devil",
    name: "악마 날개",
    category: "accessory",
    rarity: "legendary",
    description: "어둠의 악마 날개",
    pixelArt: createPixelSvg([
      "BB.......BB.....",
      "BBB.....BBB.....",
      "BBBB...BBBB.....",
      "BBBBB.BBBBB.....",
      ".BBBB.BBBB......",
      "..BBB.BBB.......",
    ], { B: "#212121" }),
    position: { x: 0, y: 0 },
    scale: 1.3,
    zIndex: 65,
    price: 5500,
    dropRate: 1.5,
    stats: { charm: 45, luck: 20 },
  },
  {
    id: "acc_bow_red",
    name: "빨간 리본",
    category: "accessory",
    rarity: "common",
    description: "귀여운 빨간 리본",
    pixelArt: createPixelSvg([
      "RR...RR.........",
      "RRRRRRR.........",
      ".RRRRR..........",
      "RR...RR.........",
    ], { R: "#F44336" }),
    position: { x: 20, y: -30 },
    scale: 0.8,
    zIndex: 95,
    price: 80,
    dropRate: 18,
    stats: { charm: 8 },
  },
  {
    id: "acc_scarf",
    name: "목도리",
    category: "accessory",
    rarity: "common",
    description: "따뜻한 목도리",
    pixelArt: createPixelSvg([
      "RRRRRRRRRR......",
      ".RRRRRRRR.......",
      "..RRRRRR........",
      "...RRRR.........",
      "....RR..........",
    ], { R: "#F44336" }),
    position: { x: 0, y: 20 },
    scale: 1,
    zIndex: 75,
    price: 100,
    dropRate: 16,
    stats: { happiness: 10 },
  },
  {
    id: "acc_backpack",
    name: "가방",
    category: "accessory",
    rarity: "rare",
    description: "귀여운 가방",
    pixelArt: createPixelSvg([
      "..BBBB..........",
      ".BBBBBB.........",
      ".BWWWWB.........",
      ".BBBBBB.........",
      ".BBBBBB.........",
    ], { B: "#8D6E63", W: "#FAFAFA" }),
    position: { x: -30, y: 10 },
    scale: 0.9,
    zIndex: 60,
    price: 300,
    dropRate: 10,
    stats: { luck: 10 },
  },
  {
    id: "acc_earrings_diamond",
    name: "다이아 귀걸이",
    category: "accessory",
    rarity: "epic",
    description: "빛나는 다이아몬드 귀걸이",
    pixelArt: createPixelSvg([
      "D.........D.....",
      "DD.......DD.....",
      ".D.......D......",
    ], { D: "#B3E5FC" }),
    position: { x: 0, y: 5 },
    scale: 1,
    zIndex: 95,
    price: 1500,
    dropRate: 5,
    stats: { charm: 30 },
  },
  {
    id: "acc_tail_cat",
    name: "고양이 꼬리",
    category: "accessory",
    rarity: "rare",
    description: "흔들흔들 고양이 꼬리",
    pixelArt: createPixelSvg([
      ".........B......",
      "........BB......",
      ".......BB.......",
      "......BB........",
      ".....BB.........",
      "....BB..........",
    ], { B: "#212121" }),
    position: { x: -35, y: 30 },
    scale: 1,
    zIndex: 55,
    price: 400,
    dropRate: 9,
    stats: { charm: 15 },
  },
  {
    id: "acc_tail_devil",
    name: "악마 꼬리",
    category: "accessory",
    rarity: "epic",
    description: "뾰족한 악마 꼬리",
    pixelArt: createPixelSvg([
      ".........RR.....",
      "........RR......",
      ".......RR.......",
      "......RR........",
      ".....RR.........",
      "....RRR.........",
    ], { R: "#D32F2F" }),
    position: { x: -35, y: 30 },
    scale: 1,
    zIndex: 55,
    price: 900,
    dropRate: 6,
    stats: { luck: 15 },
  },
  {
    id: "acc_watch_gold",
    name: "금시계",
    category: "accessory",
    rarity: "epic",
    description: "고급스러운 금시계",
    pixelArt: createPixelSvg([
      "..GGG...........",
      ".GWWWG..........",
      ".GWBWG..........",
      ".GWWWG..........",
      "..GGG...........",
    ], { G: "#FFD700", W: "#FAFAFA", B: "#212121" }),
    position: { x: -28, y: 20 },
    scale: 0.8,
    zIndex: 95,
    price: 1200,
    dropRate: 5,
    stats: { charm: 25, luck: 10 },
  },
  {
    id: "acc_bubble_tea",
    name: "버블티",
    category: "accessory",
    rarity: "rare",
    description: "맛있는 버블티",
    pixelArt: createPixelSvg([
      "....BB..........",
      "...WWWW.........",
      "..WPPPWW........",
      "..WBBBWW........",
      "...WWWW.........",
    ], { W: "#FAFAFA", P: "#F48FB1", B: "#5D4037" }),
    position: { x: 35, y: 15 },
    scale: 0.9,
    zIndex: 95,
    price: 350,
    dropRate: 9,
    stats: { happiness: 15 },
  },
  {
    id: "acc_flower",
    name: "꽃",
    category: "accessory",
    rarity: "common",
    description: "예쁜 꽃 한 송이",
    pixelArt: createPixelSvg([
      "..RRR...........",
      ".RRYRR..........",
      "..RRR...........",
      "...G............",
      "...G............",
    ], { R: "#F44336", Y: "#FFEB3B", G: "#4CAF50" }),
    position: { x: 25, y: -25 },
    scale: 0.8,
    zIndex: 95,
    price: 60,
    dropRate: 18,
    stats: { charm: 5, happiness: 5 },
  },
  {
    id: "acc_sword",
    name: "검",
    category: "accessory",
    rarity: "epic",
    description: "용사의 검",
    pixelArt: createPixelSvg([
      "......G.........",
      ".....GGG........",
      "....GGGGG.......",
      "...GGGGGGG......",
      "....BBB.........",
      "....BBB.........",
      "....YYY.........",
    ], { G: "#90A4AE", B: "#8D6E63", Y: "#FFD700" }),
    position: { x: 40, y: 5 },
    scale: 1,
    zIndex: 95,
    price: 1400,
    dropRate: 5,
    stats: { luck: 20 },
  },
  {
    id: "acc_shield",
    name: "방패",
    category: "accessory",
    rarity: "epic",
    description: "튼튼한 방패",
    pixelArt: createPixelSvg([
      "..GGGGG.........",
      ".GGGGGGG........",
      "GGGGRGGG........",
      ".GGGRGGG........",
      "..GGRGG.........",
      "...GGG..........",
      "....G...........",
    ], { G: "#90A4AE", R: "#D32F2F" }),
    position: { x: -40, y: 10 },
    scale: 1,
    zIndex: 95,
    price: 1300,
    dropRate: 5,
    stats: { luck: 18 },
  },
  {
    id: "acc_magic_wand",
    name: "마법 지팡이",
    category: "accessory",
    rarity: "legendary",
    description: "강력한 마법 지팡이",
    pixelArt: createPixelSvg([
      "....SSS.........",
      "...SSSSS........",
      "....SSS.........",
      ".....B..........",
      ".....B..........",
      ".....B..........",
      ".....B..........",
    ], { S: "#FFD700", B: "#8D6E63" }),
    position: { x: 35, y: 0 },
    scale: 1,
    zIndex: 95,
    price: 5000,
    dropRate: 2,
    stats: { luck: 40, charm: 20 },
  },

  // ==================== 펫 (PET) - 10개 ====================
  {
    id: "pet_cat",
    name: "고양이",
    category: "pet",
    rarity: "rare",
    description: "귀여운 고양이 친구",
    pixelArt: createPixelSvg([
      ".GG...GG........",
      "GGGGGGGG........",
      "GB.GGB.G........",
      "GGGGGGGG........",
      ".GGGGGG.........",
      "..G..G..........",
    ], { G: "#FF9800", B: "#212121" }),
    position: { x: 55, y: 40 },
    scale: 0.8,
    zIndex: 50,
    price: 800,
    dropRate: 7,
    stats: { happiness: 25 },
  },
  {
    id: "pet_dog",
    name: "강아지",
    category: "pet",
    rarity: "rare",
    description: "충성스러운 강아지 친구",
    pixelArt: createPixelSvg([
      "BB....BB........",
      "BBBBBBB.........",
      "BW.BBW.B........",
      "BBBBBBB.........",
      ".BBBBB..........",
      "..B..B..........",
    ], { B: "#8D6E63", W: "#212121" }),
    position: { x: 55, y: 40 },
    scale: 0.8,
    zIndex: 50,
    price: 800,
    dropRate: 7,
    stats: { happiness: 25 },
  },
  {
    id: "pet_bunny",
    name: "토끼",
    category: "pet",
    rarity: "rare",
    description: "폭신폭신한 토끼",
    pixelArt: createPixelSvg([
      ".WW.WW..........",
      ".WWWWW..........",
      "WP.WW.PW........",
      ".WWWWW..........",
      "..WWW...........",
      "..W.W...........",
    ], { W: "#FAFAFA", P: "#F48FB1" }),
    position: { x: 55, y: 40 },
    scale: 0.8,
    zIndex: 50,
    price: 750,
    dropRate: 8,
    stats: { happiness: 22, charm: 10 },
  },
  {
    id: "pet_chick",
    name: "병아리",
    category: "pet",
    rarity: "common",
    description: "삐약삐약 병아리",
    pixelArt: createPixelSvg([
      "..YYY...........",
      ".YYYYY..........",
      ".YB.BY..........",
      ".YYOYY..........",
      "..YYY...........",
    ], { Y: "#FFEB3B", B: "#212121", O: "#FF9800" }),
    position: { x: 55, y: 45 },
    scale: 0.7,
    zIndex: 50,
    price: 200,
    dropRate: 15,
    stats: { happiness: 15 },
  },
  {
    id: "pet_dragon",
    name: "아기 드래곤",
    category: "pet",
    rarity: "legendary",
    description: "전설의 아기 드래곤",
    pixelArt: createPixelSvg([
      ".GG...GG........",
      "GGGGGGGGG.......",
      "GRG.GRG.G.......",
      ".GGGGGGG........",
      "..GGGGG.........",
      ".GG.G.GG........",
    ], { G: "#4CAF50", R: "#F44336" }),
    position: { x: 55, y: 35 },
    scale: 0.9,
    zIndex: 50,
    price: 8000,
    dropRate: 1.5,
    stats: { happiness: 40, luck: 30 },
  },
  {
    id: "pet_unicorn",
    name: "유니콘",
    category: "pet",
    rarity: "mythic",
    description: "신비로운 유니콘",
    pixelArt: createPixelSvg([
      "...G............",
      "..GG............",
      ".WWWWW..........",
      "WW.WWW.W........",
      ".WWWWWW.........",
      "..W..W..........",
    ], { W: "#FAFAFA", G: "#FFD700" }),
    position: { x: 55, y: 35 },
    scale: 0.9,
    zIndex: 50,
    price: 20000,
    dropRate: 0.5,
    stats: { happiness: 50, luck: 40, charm: 30 },
  },
  {
    id: "pet_slime_mini",
    name: "미니 슬라임",
    category: "pet",
    rarity: "epic",
    description: "작은 슬라임 친구",
    pixelArt: createPixelSvg([
      "..GGG...........",
      ".GGGGG..........",
      "GB.GGB.G........",
      ".GGGGG..........",
      "..GGG...........",
    ], { G: "#81C784", B: "#212121" }),
    position: { x: 55, y: 45 },
    scale: 0.7,
    zIndex: 50,
    price: 1500,
    dropRate: 5,
    stats: { happiness: 30 },
  },
  {
    id: "pet_ghost",
    name: "유령",
    category: "pet",
    rarity: "epic",
    description: "귀여운 유령 친구",
    pixelArt: createPixelSvg([
      "..WWW...........",
      ".WWWWW..........",
      "WB.WWB.W........",
      ".WWWWW..........",
      "W.W.W.W.........",
    ], { W: "#FAFAFA", B: "#212121" }),
    position: { x: 55, y: 40 },
    scale: 0.8,
    zIndex: 50,
    price: 1200,
    dropRate: 5,
    stats: { luck: 25 },
  },
  {
    id: "pet_fairy",
    name: "요정",
    category: "pet",
    rarity: "legendary",
    description: "반짝이는 요정",
    pixelArt: createPixelSvg([
      "..YYY...........",
      ".YYYYY..........",
      "Y.Y.Y.Y.........",
      ".YYYYY..........",
      "..Y.Y...........",
    ], { Y: "#FFD700" }),
    position: { x: 55, y: 35 },
    scale: 0.8,
    zIndex: 50,
    price: 7000,
    dropRate: 2,
    stats: { luck: 35, happiness: 25 },
  },
  {
    id: "pet_robot",
    name: "로봇",
    category: "pet",
    rarity: "epic",
    description: "작은 로봇 친구",
    pixelArt: createPixelSvg([
      "..GGG...........",
      ".GGGGG..........",
      "GB.GGB.G........",
      ".GGRGG..........",
      "..GGG...........",
      "..G.G...........",
    ], { G: "#90A4AE", B: "#2196F3", R: "#F44336" }),
    position: { x: 55, y: 40 },
    scale: 0.8,
    zIndex: 50,
    price: 1400,
    dropRate: 5,
    stats: { luck: 20 },
  },

  // ==================== 배경 (BACKGROUND) - 10개 ====================
  {
    id: "bg_sunset",
    name: "노을 배경",
    category: "background",
    rarity: "rare",
    description: "아름다운 노을",
    pixelArt: "linear-gradient(180deg, #FF6B6B 0%, #FFB347 50%, #4ECDC4 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 500,
    dropRate: 8,
  },
  {
    id: "bg_night",
    name: "밤하늘 배경",
    category: "background",
    rarity: "rare",
    description: "별이 빛나는 밤",
    pixelArt: "linear-gradient(180deg, #0D1B2A 0%, #1B263B 50%, #415A77 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 500,
    dropRate: 8,
  },
  {
    id: "bg_sakura",
    name: "벚꽃 배경",
    category: "background",
    rarity: "epic",
    description: "봄의 벚꽃",
    pixelArt: "linear-gradient(180deg, #FFB7C5 0%, #FFDEE9 50%, #B5FFFC 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 1200,
    dropRate: 5,
    stats: { happiness: 15 },
  },
  {
    id: "bg_ocean",
    name: "바다 배경",
    category: "background",
    rarity: "rare",
    description: "시원한 바다",
    pixelArt: "linear-gradient(180deg, #87CEEB 0%, #4FC3F7 50%, #0288D1 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 450,
    dropRate: 9,
  },
  {
    id: "bg_forest",
    name: "숲 배경",
    category: "background",
    rarity: "rare",
    description: "평화로운 숲",
    pixelArt: "linear-gradient(180deg, #A8E6CF 0%, #56AB91 50%, #2E7D32 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 450,
    dropRate: 9,
  },
  {
    id: "bg_galaxy",
    name: "은하수 배경",
    category: "background",
    rarity: "legendary",
    description: "신비로운 은하수",
    pixelArt: "linear-gradient(180deg, #0D0D1A 0%, #1A1A40 30%, #4A1A6B 60%, #7B2CBF 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 4000,
    dropRate: 2,
    stats: { luck: 20 },
  },
  {
    id: "bg_rainbow",
    name: "무지개 배경",
    category: "background",
    rarity: "epic",
    description: "행복한 무지개",
    pixelArt: "linear-gradient(180deg, #FF6B6B 0%, #FFE66D 20%, #4ECDC4 40%, #4FC3F7 60%, #9C27B0 80%, #E91E63 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 1500,
    dropRate: 5,
    stats: { happiness: 25 },
  },
  {
    id: "bg_candy",
    name: "캔디 배경",
    category: "background",
    rarity: "epic",
    description: "달콤한 캔디나라",
    pixelArt: "linear-gradient(180deg, #FFB6C1 0%, #FF69B4 50%, #FF1493 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 1100,
    dropRate: 5,
    stats: { happiness: 20 },
  },
  {
    id: "bg_snow",
    name: "눈 내리는 배경",
    category: "background",
    rarity: "rare",
    description: "겨울 눈",
    pixelArt: "linear-gradient(180deg, #E3F2FD 0%, #BBDEFB 50%, #90CAF9 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 500,
    dropRate: 8,
  },
  {
    id: "bg_aurora",
    name: "오로라 배경",
    category: "background",
    rarity: "mythic",
    description: "환상적인 오로라",
    pixelArt: "linear-gradient(180deg, #0D1B2A 0%, #00C853 30%, #00BCD4 60%, #E040FB 100%)",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 0,
    price: 15000,
    dropRate: 0.5,
    stats: { luck: 40, happiness: 30 },
  },

  // ==================== 이펙트 (EFFECT) - 10개 ====================
  {
    id: "effect_sparkle",
    name: "반짝임",
    category: "effect",
    rarity: "rare",
    description: "반짝반짝 이펙트",
    pixelArt: "✨",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 600,
    dropRate: 8,
    stats: { charm: 15 },
  },
  {
    id: "effect_hearts",
    name: "하트",
    category: "effect",
    rarity: "rare",
    description: "둥둥 떠다니는 하트",
    pixelArt: "💕",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 600,
    dropRate: 8,
    stats: { charm: 15 },
  },
  {
    id: "effect_stars",
    name: "별",
    category: "effect",
    rarity: "rare",
    description: "빛나는 별 이펙트",
    pixelArt: "⭐",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 600,
    dropRate: 8,
    stats: { luck: 15 },
  },
  {
    id: "effect_fire",
    name: "불꽃",
    category: "effect",
    rarity: "epic",
    description: "타오르는 불꽃",
    pixelArt: "🔥",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 1200,
    dropRate: 5,
    stats: { charm: 25 },
  },
  {
    id: "effect_snow",
    name: "눈",
    category: "effect",
    rarity: "rare",
    description: "흩날리는 눈",
    pixelArt: "❄️",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 550,
    dropRate: 9,
  },
  {
    id: "effect_rainbow",
    name: "무지개빛",
    category: "effect",
    rarity: "legendary",
    description: "무지개빛 아우라",
    pixelArt: "🌈",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 5000,
    dropRate: 2,
    stats: { charm: 40, happiness: 20 },
  },
  {
    id: "effect_lightning",
    name: "번개",
    category: "effect",
    rarity: "epic",
    description: "번쩍이는 번개",
    pixelArt: "⚡",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 1100,
    dropRate: 5,
    stats: { luck: 20 },
  },
  {
    id: "effect_music",
    name: "음표",
    category: "effect",
    rarity: "rare",
    description: "흥겨운 음표",
    pixelArt: "🎵",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 500,
    dropRate: 9,
    stats: { happiness: 15 },
  },
  {
    id: "effect_confetti",
    name: "꽃가루",
    category: "effect",
    rarity: "epic",
    description: "축하 꽃가루",
    pixelArt: "🎊",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 1000,
    dropRate: 6,
    stats: { happiness: 25 },
  },
  {
    id: "effect_galaxy",
    name: "은하 이펙트",
    category: "effect",
    rarity: "mythic",
    description: "우주의 신비",
    pixelArt: "🌌",
    position: { x: 0, y: 0 },
    scale: 1,
    zIndex: 200,
    price: 18000,
    dropRate: 0.5,
    stats: { charm: 50, luck: 40 },
  },
];

// 아이템 검색 헬퍼
export function getItemById(id: string): GameItem | undefined {
  return ITEMS_DATABASE.find((item) => item.id === id);
}

export function getItemsByCategory(category: ItemCategory): GameItem[] {
  return ITEMS_DATABASE.filter((item) => item.category === category);
}

export function getItemsByRarity(rarity: ItemRarity): GameItem[] {
  return ITEMS_DATABASE.filter((item) => item.rarity === rarity);
}

// 가챠 드롭 계산
export function calculateGachaDrop(): GameItem {
  const roll = Math.random() * 100;
  let cumulative = 0;

  // 등급별 확률 계산
  const rarities: ItemRarity[] = ["mythic", "legendary", "epic", "rare", "common"];
  let selectedRarity: ItemRarity = "common";

  for (const rarity of rarities) {
    cumulative += RARITY_CONFIG[rarity].dropRate;
    if (roll < cumulative) {
      selectedRarity = rarity;
      break;
    }
  }

  // 해당 등급 아이템 중 랜덤 선택
  const items = getItemsByRarity(selectedRarity);
  return items[Math.floor(Math.random() * items.length)];
}
