# Generated by Django 4.2.27 on 2026-01-03 04:05

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_ticket_entry_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='ticket',
            name='team',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='faqattachment',
            name='file',
            field=models.FileField(upload_to=support.models._upload_to_faq),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=support.models._upload_to_ticket),
        ),
        migrations.AlterField(
            model_name='ticketreplyattachment',
            name='file',
            field=models.FileField(upload_to=support.models._upload_to_reply),
        ),
    ]
