# Generated by Django 4.2.27 on 2026-01-03 04:17

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_supportteam_profile_status_message_ticket_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to=support.models._upload_to_avatar),
        ),
    ]
