# Generated by Django 4.2.27 on 2026-02-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0026_faqcategory_created_at_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('shortcut', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='admininboxview',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SupportChannel',
        ),
        migrations.DeleteModel(
            name='SupportTag',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'FAQ categories'},
        ),
        migrations.AlterModelOptions(
            name='supportteam',
            options={'ordering': ['order', 'key']},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Ticket categories'},
        ),
        migrations.AlterModelOptions(
            name='ticketnote',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Ticket replies'},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='form_default_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='guide_description',
            field=models.TextField(blank=True, default='아래 안내를 확인하고 문의를 접수하면 더 빠르게 도와드릴 수 있어요.'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='platform',
            field=models.CharField(choices=[('ALL', '전체'), ('ANDROID', '안드로이드'), ('IOS', 'iOS')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='guide_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='kind',
            field=models.CharField(choices=[('GENERAL', '일반'), ('GUIDE', '가이드')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportteam',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supportteam',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportteam',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', '낮음'), ('NORMAL', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', '진행중'), ('ANSWERED', '보류'), ('CLOSED', '완료')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='bot_title',
            field=models.CharField(blank=True, default='주디 서포트봇', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='form_button_label',
            field=models.CharField(blank=True, default='기본 양식 넣기', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='form_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='form_title_template',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdminInboxView',
        ),
    ]
