# Generated by Django 4.2.27 on 2026-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_appsettings_chattemplate_remove_admininboxview_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
